# serverless.yml

service: serverless-express-mongo-base

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: app/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'